name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  documentation:

    runs-on: windows-latest

    if: ${{ !contains(github.event.head_commit.message, 'Automated documentation update') }}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_PAT }}
    - name: Generate Rust documentation
      working-directory: ./src-tauri
      run: cargo doc --no-deps --document-private-items --target-dir ../docs
    - name: Commit documentation
      run: |
          git config --global user.name 'William Watson'
          git config --global user.email 'williamdwatson@users.noreply.github.com'
          git add -A
          git commit -m "Automated documentation update"
          git push
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
